apiVersion: v1
kind: ConfigMap
metadata:
  name: swiftpay-config
  namespace: swiftpay
data:
  DB_URL: jdbc:postgresql://postgres:5432/swiftpay
  DB_USERNAME: swiftpay
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
