apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: swiftpay
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: swiftpay
            - name: POSTGRES_USER
              value: swiftpay
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swiftpay-secret
                  key: DB_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "swiftpay", "-d", "swiftpay"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: swiftpay
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
